server:
  port:  9999
  servlet:
    context-path:  /ENOS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enosyw?useUnicode=true&serverTimezone=GMT%2b8&characterEncoding=utf8 
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    
#####datasource druid pool
    druid: 
     filters: stat
     initial-size: 10
     max-active: 20
     min-idle: 5
######druid监控配置
### WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
##是否启用StatFilter默认值true
#     
#     enabled: true
#     web-stat-filter: 
#       url-pattern: /*
#    
##      exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
##session统计功能
##        session-stat-enable:  true
##最大session数
#       session-stat-max-count: 100000
##你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
#       principal-session-name: admin
##你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
#       principal-cookie-name: admin
# #置profileEnable能够监控单个url调用的sql列表。
#       profile-enable: true
### StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
#     stat-view-servlet: 
#       enabled: true
#       url-pattern: /druid/*
#       reset-enable: true
#       login-username: admin
#       login-password: 123456
#       allow: 192.168.200.58
#       deny: 192.168.10.1
#
### Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
## Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#     aop-patterns: org.lsh.dubhe.service.*
#
##配置wall filter 
#     filter:
#      wall:
#       enabled: true
#       db-type: mysql
#       config:
#         alter-table-allow: false
#         truncate-allow: false
#         drop-table-allow: false
##是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL。
#         none-base-statement-allow: false
##检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
#         update-where-none-check: true
##SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
#         elect-into-outfile-allow: false
##是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
#         metadata-allow: true
##对被认为是攻击的SQL进行LOG.error输出
#       log-violation: true
##对被认为是攻击的SQL抛出SQLExcepton
#       throw-exception: true
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
  profiles:
    active: dev
  thymeleaf:
    prefix:  classpath:/templates/
    suffix:  .html
    mode: LEGACYHTML5
    encoding:  UTF-8
    cache:  false
    servlet:
      content-type:  text/html
mybatis:
  mapper-locations:  classpath:/mapper/*.xml
  
    
